groups:
  - name: capstone-app
    rules:
      - alert: AppCrashing
        expr: increase(app_crash_total[1m]) > 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "服務 https://workshop-{{ $labels.student }}.ocean1029.com crashed"
          description: "收到 crash request，恭喜你完成工作坊內容 🎉"
